[project]
name = "camino-buzz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beeware>=0.3.0",
    "briefcase>=0.3.22",
    "markdown>=3.7",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
